Repository allure-framework/allure-kotlin, pull requests merged in 2020-06, with the labels that each got.

#10 Add simple build and release actions
  .github/release-drafter.yml
  .github/workflows/build.yml
  .github/workflows/release-draft.yml
  .github/workflows/release.yml
  build.gradle.kts
  gradle.properties
  gradle/github-publish.gradle
Labels: type:improvement

#11 Fix release (add publish action)
  .github/workflows/release.yml
Labels: type:bug

#12 Fix release credentials (env variable)
  .github/workflows/release.yml
Labels: type:bug

#13 Create LICENSE
  LICENSE
  README.md
Labels: type:improvement

#14 fix "Commits since" in release-drafter.yml
  .github/release-drafter.yml
Labels: type:bug

#18 add CONTRIBUTING.md
  .github/CONTRIBUTING.md
  README.md
Labels: type:improvement

#17 Setting up `allure-android`
  allure-kotlin-android/build.gradle.kts
  allure-kotlin-android/consumer-rules.pro
  allure-kotlin-android/proguard-rules.pro
  allure-kotlin-android/src/main/AndroidManifest.xml
  allure-kotlin-model/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  gradle.properties
  settings.gradle.kts
Labels: type:new feature
